CREATE INDEX IX_Users_LastAccessDate ON Users(LastAccessDate);
SET STATISTICS TIME ON;
SET STATISTICS IO ON;
SELECT DisplayName, LastAccessDate
FROM Users
ORDER BY LastAccessDate DESC;
SET STATISTICS TIME OFF;
SET STATISTICS IO OFF;
