CREATE INDEX IX_PostTypes_Id ON PostTypes(Id);
SET STATISTICS TIME ON;
SET STATISTICS IO ON;
SELECT *
FROM Posts
JOIN PostTypes ON Posts.PostTypeId = PostTypes.Id
WHERE PostTypes.Id = 1;
SET STATISTICS TIME OFF;
SET STATISTICS IO OFF;
